// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.23.8";
import { PDP_PRODUCTS } from "npm:@/lib/pdpProducts";
var list_products_default = defineTool({
  name: "list_products",
  title: "List INSULFILM products",
  description: "List every INSULFILM\u2122 product available on the site (slug, commercial name, page URL, and category).",
  inputSchema: {
    lang: z.enum(["pt", "en", "es"]).default("pt").describe("Language for the returned category label (pt, en, or es).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ lang }) => {
    const items = Object.entries(PDP_PRODUCTS).map(([slug, p]) => ({
      slug,
      name: p.name,
      url: p.url,
      category: p.category?.[lang] ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { products: items }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.23.8";
import { PDP_PRODUCTS as PDP_PRODUCTS2 } from "npm:@/lib/pdpProducts";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get INSULFILM product details",
  description: "Return full public details for one INSULFILM\u2122 product: description, technical properties, category, rating, and page URL.",
  inputSchema: {
    slug: z2.string().min(1).describe("Product slug, e.g. 'matrix', 'eclipse', 'raystart'."),
    lang: z2.enum(["pt", "en", "es"]).default("pt").describe("Language for text fields.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug, lang }) => {
    const p = PDP_PRODUCTS2[slug];
    if (!p) {
      return {
        content: [{ type: "text", text: `No product found for slug '${slug}'.` }],
        isError: true
      };
    }
    const data = {
      slug,
      name: p.name,
      description: p.description[lang],
      url: p.url,
      category: p.category?.[lang] ?? null,
      properties: p.properties.map((prop) => ({
        name: prop.name[lang],
        value: prop.value[lang]
      })),
      rating: p.rating ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/get-faqs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.23.8";
import { getPDPFaqs } from "npm:@/lib/pdpFAQs";
var get_faqs_default = defineTool3({
  name: "get_faqs",
  title: "Get product FAQs",
  description: "Return the public FAQ list (question/answer pairs) for one INSULFILM\u2122 product page.",
  inputSchema: {
    slug: z3.string().min(1).describe("Product slug, e.g. 'matrix', 'eclipse'."),
    lang: z3.enum(["pt", "en", "es"]).default("pt").describe("Language for the FAQs.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug, lang }) => {
    const faqs = getPDPFaqs(slug, lang);
    if (!faqs) {
      return {
        content: [{ type: "text", text: `No FAQs found for slug '${slug}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(faqs, null, 2) }],
      structuredContent: { faqs }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "insulfilm-mcp",
  title: "INSULFILM\u2122 Site MCP",
  version: "0.1.0",
  instructions: "Public tools for the INSULFILM\u2122 site. Use `list_products` to discover products, `get_product` for full specs of a product by slug, and `get_faqs` to fetch the public FAQ for a product. All content is public and available in Portuguese (pt), English (en), and Spanish (es).",
  tools: [list_products_default, get_product_default, get_faqs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
