// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.23.8";

// src/lib/pdpProducts.ts
var CAT_AUTO_SOLAR = {
  pt: "Pel\xEDcula automotiva, prote\xE7\xE3o solar",
  en: "Automotive window film, solar protection",
  es: "Pel\xEDcula automotriz, protecci\xF3n solar"
};
var CAT_AUTO_SECURITY = {
  pt: "Pel\xEDcula automotiva, seguran\xE7a",
  en: "Automotive window film, security",
  es: "Pel\xEDcula automotriz, seguridad"
};
var CAT_AUTO_PPF = {
  pt: "Pel\xEDcula de prote\xE7\xE3o de pintura (PPF) automotiva",
  en: "Automotive Paint Protection Film (PPF)",
  es: "Pel\xEDcula de protecci\xF3n de pintura (PPF) automotriz"
};
var CAT_ARQ_SOLAR = {
  pt: "Pel\xEDcula arquitet\xF4nica, controle solar",
  en: "Architectural window film, solar control",
  es: "Pel\xEDcula arquitect\xF3nica, control solar"
};
var CAT_ARQ_SPF = {
  pt: "Pel\xEDcula arquitet\xF4nica, prote\xE7\xE3o de superf\xEDcies (SPF)",
  en: "Architectural Surface Protection Film (SPF)",
  es: "Pel\xEDcula arquitect\xF3nica, protecci\xF3n de superficies (SPF)"
};
var P = (pt, en, es, valuePt, valueEn, valueEs) => ({
  name: { pt, en, es },
  value: { pt: valuePt, en: valueEn ?? valuePt, es: valueEs ?? valuePt }
});
var TECH = (pt, en, es) => P("Tecnologia", "Technology", "Tecnolog\xEDa", pt, en ?? pt, es ?? pt);
var WARRANTY = (years) => P("Garantia", "Warranty", "Garant\xEDa", `${years} anos`, `${years} years`, `${years} a\xF1os`);
var WARRANTY_UPTO = (years) => P("Garantia", "Warranty", "Garant\xEDa", `At\xE9 ${years} anos`, `Up to ${years} years`, `Hasta ${years} a\xF1os`);
var IR = (value) => P("Rejei\xE7\xE3o de Infravermelho", "Infrared Rejection", "Rechazo de Infrarrojos", value);
var IR_UPTO = (pt, en, es) => P("Rejei\xE7\xE3o de Infravermelho", "Infrared Rejection", "Rechazo de Infrarrojos", pt, en, es);
var VLT = (value) => P("Transmiss\xE3o de Luz", "Visible Light Transmission", "Transmisi\xF3n de Luz", value);
var THICK = (value) => P("Espessura", "Thickness", "Espesor", value);
var PDP_PRODUCTS = {
  // ═══ AUTOMOTIVO, SOLAR ═══
  matrix: {
    name: "INSULFILM\u2122 Matrix",
    description: {
      pt: "Pel\xEDcula premium de nano cer\xE2mica verdadeira. Rejei\xE7\xE3o de at\xE9 75% dos raios infravermelhos e 10 anos de garantia.",
      en: "Premium true nano-ceramic window film. Up to 75% infrared rejection and 10-year warranty.",
      es: "Pel\xEDcula premium de nano cer\xE1mica verdadera. Hasta 75% de rechazo de infrarrojos y 10 a\xF1os de garant\xEDa."
    },
    url: "/matrix",
    category: CAT_AUTO_SOLAR,
    properties: [
      TECH("Nano Cer\xE2mica", "Nano Ceramic", "Nano Cer\xE1mica"),
      IR_UPTO("At\xE9 75%", "Up to 75%", "Hasta 75%"),
      WARRANTY("10")
    ],
    rating: { value: 4.9, count: 312 },
    offer: true
  },
  "polariz-ultra": {
    name: "INSULFILM\u2122 Polariz Ultra",
    description: {
      pt: "Prote\xE7\xE3o solar com visual polarizado elegante. H\xEDbrida metal-cer\xE2mica com 75% de rejei\xE7\xE3o de IR e 10 anos de garantia.",
      en: "Solar protection with elegant polarized look. Metal-ceramic hybrid, 75% IR rejection and 10-year warranty.",
      es: "Protecci\xF3n solar con apariencia polarizada elegante. H\xEDbrida metal-cer\xE1mica con 75% de rechazo IR y 10 a\xF1os de garant\xEDa."
    },
    url: "/polariz-ultra",
    category: CAT_AUTO_SOLAR,
    properties: [
      TECH("H\xEDbrida Metal-Cer\xE2mica", "Metal-Ceramic Hybrid", "H\xEDbrida Metal-Cer\xE1mica"),
      IR_UPTO("At\xE9 75%", "Up to 75%", "Hasta 75%"),
      WARRANTY("10")
    ],
    rating: { value: 4.9, count: 189 },
    offer: true
  },
  // ═══ AUTOMOTIVO, PPF ═══
  "phantom-gloss": {
    name: "INSULFILM\u2122 Phantom Gloss",
    description: {
      pt: "Surface Protection Film para superf\xEDcies brilhosas. Preserva o brilho original contra micro-riscos, manchas \xE1cidas e desgaste. 180 microns. Garantia 5 anos.",
      en: "Surface Protection Film for glossy surfaces. Preserves original gloss against micro-scratches, acid stains and wear. 180 microns. 5-year warranty.",
      es: "Surface Protection Film para superficies brillantes. Preserva el brillo original contra micro-rayones, manchas \xE1cidas y desgaste. 180 micras. Garant\xEDa 5 a\xF1os."
    },
    url: "/phantom-gloss",
    category: CAT_AUTO_PPF,
    properties: [
      P("Tipo", "Type", "Tipo", "SPF, Surface Protection Film"),
      THICK("180 microns (7 mil)"),
      WARRANTY("5")
    ],
    rating: { value: 4.9, count: 156 },
    offer: true
  },
  // ═══ AUTOMOTIVO, SEGURANÇA ═══
  antivandalismo13k: {
    name: "INSULFILM\u2122 Antivandalismo 13K",
    description: {
      pt: "Prote\xE7\xE3o contra atos de vandalismo. Estrutura multicamadas de 12 mil com dupla lamina\xE7\xE3o e 5 anos de garantia.",
      en: "Protection against vandalism. 12-mil multilayer structure with double lamination and 5-year warranty.",
      es: "Protecci\xF3n contra actos de vandalismo. Estructura multicapa de 12 mil con doble laminaci\xF3n y 5 a\xF1os de garant\xEDa."
    },
    url: "/antivandalismo13k",
    category: CAT_AUTO_SECURITY,
    properties: [
      THICK("12 mil / 304,8 micras"),
      P("Estrutura", "Structure", "Estructura", "Dupla Lamina\xE7\xE3o", "Double Lamination", "Doble Laminaci\xF3n"),
      WARRANTY("5")
    ],
    rating: { value: 4.9, count: 274 },
    offer: true
  },
  skinsafe8k: {
    name: "INSULFILM\u2122 SkinSafe8K",
    description: {
      pt: "Pel\xEDcula de prote\xE7\xE3o (7 mil / 177,8 micras) para lamina\xE7\xE3o do vidro em quebras acidentais. Minimiza a proje\xE7\xE3o de estilha\xE7os contra os ocupantes. 5 anos de garantia.",
      en: "Protection film (7 mil / 177.8 microns) that laminates glass in accidental breakage. Minimizes shard projection toward occupants. 5-year warranty.",
      es: "Pel\xEDcula de protecci\xF3n (7 mil / 177,8 micras) para laminaci\xF3n del vidrio en roturas accidentales. Minimiza la proyecci\xF3n de astillas contra los ocupantes. 5 a\xF1os de garant\xEDa."
    },
    url: "/skinsafe8k",
    category: CAT_AUTO_SECURITY,
    properties: [
      THICK("7 mil / 177,8 micras"),
      P(
        "Fun\xE7\xE3o",
        "Function",
        "Funci\xF3n",
        "Lamina\xE7\xE3o do vidro, prote\xE7\xE3o contra estilha\xE7os",
        "Glass lamination, shard protection",
        "Laminaci\xF3n del vidrio, protecci\xF3n contra astillas"
      ),
      WARRANTY("5")
    ],
    rating: { value: 4.8, count: 201 },
    offer: true
  },
  skudoguard: {
    name: "INSULFILM\u2122 SkudoGuard",
    description: {
      pt: "Escudo forte e efetivo contra armas brancas. Estrutura de 16 mil com for\xE7a de ruptura de 440 lbs/in. 10 anos de garantia.",
      en: "Strong and effective shield against bladed weapons. 16-mil structure with 440 lbs/in break strength. 10-year warranty.",
      es: "Escudo fuerte y efectivo contra armas blancas. Estructura de 16 mil con fuerza de ruptura de 440 lbs/in. 10 a\xF1os de garant\xEDa."
    },
    url: "/skudoguard",
    category: CAT_AUTO_SECURITY,
    properties: [
      THICK("16 mil / 406,4 micras"),
      P("For\xE7a de Ruptura", "Break Strength", "Fuerza de Ruptura", "440 lbs/in"),
      WARRANTY("10")
    ],
    rating: { value: 4.9, count: 167 },
    offer: true
  },
  "skudo-ultra": {
    name: "INSULFILM\u2122 SkudoUltra",
    description: {
      pt: "A prote\xE7\xE3o m\xE1xima para seus vidros laterais. Pel\xEDcula de 24 mil com tetra lamina\xE7\xE3o e 10 anos de garantia.",
      en: "Maximum protection for your side windows. 24-mil film with tetra-lamination and 10-year warranty.",
      es: "La m\xE1xima protecci\xF3n para sus vidrios laterales. Pel\xEDcula de 24 mil con tetra laminaci\xF3n y 10 a\xF1os de garant\xEDa."
    },
    url: "/skudo-ultra",
    category: CAT_AUTO_SECURITY,
    properties: [
      THICK("24 mil / 609,6 micras"),
      P("Estrutura", "Structure", "Estructura", "Tetra Lamina\xE7\xE3o", "Tetra Lamination", "Tetra Laminaci\xF3n"),
      WARRANTY("10")
    ],
    rating: { value: 5, count: 142 },
    offer: true
  },
  // ═══ ARQUITETÔNICO, SOLAR ═══
  clear70: {
    name: "INSULFILM\u2122 Clear70",
    description: {
      pt: "Pel\xEDcula arquitet\xF4nica de tecnologia nano cer\xE2mica com 72% de transpar\xEAncia, rejei\xE7\xE3o de IR de 81% e prote\xE7\xE3o UV >99%. Marca registrada.",
      en: "Architectural nano-ceramic film with 72% transparency, 81% IR rejection and >99% UV protection. Registered trademark.",
      es: "Pel\xEDcula arquitect\xF3nica de tecnolog\xEDa nano cer\xE1mica con 72% de transparencia, 81% de rechazo IR y protecci\xF3n UV >99%. Marca registrada."
    },
    url: "/arquitetonico/solar/clear70",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("Nano Ceramic Infrared Film"),
      VLT("72%"),
      IR("81%"),
      WARRANTY_UPTO("5")
    ],
    rating: { value: 4.9, count: 198 },
    offer: true
  },
  naturale: {
    name: "INSULFILM\u2122 Naturale",
    description: {
      pt: "Pel\xEDcula arquitet\xF4nica premium com tecnologia de bombardeamento i\xF4nico, at\xE9 81% de rejei\xE7\xE3o IR e garantia de 10 anos. Discri\xE7\xE3o que transforma.",
      en: "Premium architectural film with ion sputtering technology, up to 81% IR rejection and 10-year warranty. Discretion that transforms.",
      es: "Pel\xEDcula arquitect\xF3nica premium con tecnolog\xEDa de bombardeo i\xF3nico, hasta 81% de rechazo IR y garant\xEDa de 10 a\xF1os. Discreci\xF3n que transforma."
    },
    url: "/arquitetonico/solar/naturale",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("Neutral Sputtered Film"),
      IR_UPTO("At\xE9 81%", "Up to 81%", "Hasta 81%"),
      P("Vers\xF5es", "Versions", "Versiones", "4 (70, 50, 35, 20)"),
      WARRANTY_UPTO("10")
    ],
    rating: { value: 4.9, count: 176 },
    offer: true
  },
  orizzonte70: {
    name: "INSULFILM\u2122 Orizzonte70",
    description: {
      pt: "Pel\xEDcula cer\xE2mica premium com 93% de rejei\xE7\xE3o de IR, 68% de transmiss\xE3o de luz e garantia de 10 anos. O mais alto desempenho cer\xE2mico da linha.",
      en: "Premium ceramic film with 93% IR rejection, 68% visible light transmission and 10-year warranty. Highest ceramic performance in the line.",
      es: "Pel\xEDcula cer\xE1mica premium con 93% de rechazo IR, 68% de transmisi\xF3n de luz y garant\xEDa de 10 a\xF1os. El m\xE1s alto desempe\xF1o cer\xE1mico de la l\xEDnea."
    },
    url: "/arquitetonico/solar/orizzonte70",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("Premium Nano Ceramic Infrared Film"),
      VLT("68%"),
      IR("93%"),
      WARRANTY_UPTO("10")
    ],
    rating: { value: 5, count: 154 },
    offer: true
  },
  "grigio-invertito": {
    name: "INSULFILM\u2122 Grigio Invertito",
    description: {
      pt: "Pel\xEDcula arquitet\xF4nica com espelhamento invertido. Privacidade externa durante o dia, visibilidade interna preservada. Marca registrada.",
      en: "Architectural film with inverted mirror effect. Outdoor privacy during the day, indoor visibility preserved. Registered trademark.",
      es: "Pel\xEDcula arquitect\xF3nica con espejado invertido. Privacidad externa durante el d\xEDa, visibilidad interna preservada. Marca registrada."
    },
    url: "/arquitetonico/solar/grigio-invertito",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("Vapor-Coated Aluminium Film"),
      VLT("15%"),
      IR("75%"),
      WARRANTY_UPTO("3")
    ],
    rating: { value: 4.7, count: 121 },
    offer: true
  },
  "metallico-argento": {
    name: "INSULFILM\u2122 Metallico Argento",
    description: {
      pt: "Pel\xEDcula espelhada premium com at\xE9 86% de rejei\xE7\xE3o IR, prote\xE7\xE3o UV >99% e garantia de 10 anos. M\xE1xima efici\xEAncia com sofistica\xE7\xE3o espelhada.",
      en: "Premium mirrored film with up to 86% IR rejection, >99% UV protection and 10-year warranty. Maximum efficiency with mirrored sophistication.",
      es: "Pel\xEDcula espejada premium con hasta 86% de rechazo IR, protecci\xF3n UV >99% y garant\xEDa de 10 a\xF1os. M\xE1xima eficiencia con sofisticaci\xF3n espejada."
    },
    url: "/arquitetonico/solar/metallico-argento",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("Vapor-Coated Aluminium Film"),
      IR_UPTO("At\xE9 86%", "Up to 86%", "Hasta 86%"),
      P("Vers\xF5es", "Versions", "Versiones", "3 (50, 35, 20)"),
      WARRANTY_UPTO("10")
    ],
    rating: { value: 4.9, count: 138 },
    offer: true
  },
  "reflesso-d-argento": {
    name: "INSULFILM\u2122 Reflesso d'Argento",
    description: {
      pt: "Pel\xEDcula arquitet\xF4nica espelhada com 80% de rejei\xE7\xE3o de IR e privacidade diurna. Aplic\xE1vel em fachadas e pergolados. Marca registrada.",
      en: "Mirrored architectural film with 80% IR rejection and daytime privacy. Suitable for fa\xE7ades and pergolas. Registered trademark.",
      es: "Pel\xEDcula arquitect\xF3nica espejada con 80% de rechazo IR y privacidad diurna. Aplicable en fachadas y p\xE9rgolas. Marca registrada."
    },
    url: "/arquitetonico/solar/reflesso-d-argento",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("Vapor-Coated Aluminium Film"),
      IR("80%"),
      WARRANTY_UPTO("3")
    ],
    rating: { value: 4.8, count: 109 },
    offer: true
  },
  petrolio: {
    name: "INSULFILM\u2122 Petrolio",
    description: {
      pt: "Pel\xEDcula arquitet\xF4nica h\xEDbrida com est\xE9tica preta sem refletividade intensa, prote\xE7\xE3o UV >99% e rejei\xE7\xE3o de IR de at\xE9 42%. Para projetos contempor\xE2neos.",
      en: "Hybrid architectural film with black aesthetic without intense reflectivity, >99% UV protection and up to 42% IR rejection. For contemporary projects.",
      es: "Pel\xEDcula arquitect\xF3nica h\xEDbrida con est\xE9tica negra sin reflectividad intensa, protecci\xF3n UV >99% y rechazo IR de hasta 42%. Para proyectos contempor\xE1neos."
    },
    url: "/arquitetonico/solar/petrolio",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("Hybrid Performance Film"),
      IR_UPTO("At\xE9 42%", "Up to 42%", "Hasta 42%"),
      WARRANTY_UPTO("3")
    ],
    rating: { value: 4.7, count: 96 },
    offer: true
  },
  "specchiato-bronzo": {
    name: "INSULFILM\u2122 Specchiato Bronzo",
    description: {
      pt: "Pel\xEDcula espelhada bronze com tecnologia Sputtered Nichrome, at\xE9 72% de rejei\xE7\xE3o IR e conforto visual interno preservado. Garantia 10 anos.",
      en: "Bronze mirrored film with Sputtered Nichrome technology, up to 72% IR rejection and preserved indoor visual comfort. 10-year warranty.",
      es: "Pel\xEDcula espejada bronce con tecnolog\xEDa Sputtered Nichrome, hasta 72% de rechazo IR y confort visual interno preservado. Garant\xEDa 10 a\xF1os."
    },
    url: "/arquitetonico/solar/specchiato-bronzo",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("Sputtered Nichrome Film"),
      IR_UPTO("At\xE9 72%", "Up to 72%", "Hasta 72%"),
      P("Vers\xF5es", "Versions", "Versiones", "3 (35, 25, 15)"),
      WARRANTY_UPTO("10")
    ],
    rating: { value: 4.9, count: 132 },
    offer: true
  },
  ultravioletti90: {
    name: "INSULFILM\u2122 Ultravioletti90",
    description: {
      pt: "Pel\xEDcula arquitet\xF4nica incolor com bloqueio de >99% de raios UV. Prote\xE7\xE3o m\xE1xima invis\xEDvel para vidros, sem alterar est\xE9tica ou luminosidade.",
      en: "Clear architectural film blocking >99% of UV rays. Invisible maximum protection for glass, without altering aesthetics or luminosity.",
      es: "Pel\xEDcula arquitect\xF3nica incolora con bloqueo de >99% de rayos UV. Protecci\xF3n m\xE1xima invisible para vidrios, sin alterar est\xE9tica o luminosidad."
    },
    url: "/arquitetonico/solar/ultravioletti90",
    category: CAT_ARQ_SOLAR,
    properties: [
      TECH("UV Concentrated"),
      VLT("88%"),
      P("Bloqueio UV", "UV Blocking", "Bloqueo UV", ">99%"),
      WARRANTY_UPTO("5")
    ],
    rating: { value: 4.8, count: 144 },
    offer: true
  },
  // ═══ ARQUITETÔNICO, SPF ═══
  "phantom-arquitetonico": {
    name: "INSULFILM\u2122 Phantom Arquitet\xF4nico",
    description: {
      pt: "Pel\xEDcula de prote\xE7\xE3o de superf\xEDcies (SPF, Surface Protection Film) para m\xE1rmores, madeiras, a\xE7o inox e vidros. Preservando o design dos seus acabamentos.",
      en: "Surface Protection Film (SPF) for marble, wood, stainless steel and glass. Preserving the design of your finishes.",
      es: "Pel\xEDcula de protecci\xF3n de superficies (SPF, Surface Protection Film) para m\xE1rmoles, maderas, acero inoxidable y vidrios. Preservando el dise\xF1o de sus acabados."
    },
    url: "/phantom-arquitetonico",
    category: CAT_ARQ_SPF,
    properties: [
      P("Tipo", "Type", "Tipo", "SPF, Surface Protection Film"),
      P("Vers\xF5es", "Versions", "Versiones", "Gloss & Matte"),
      THICK("180 microns"),
      WARRANTY("5")
    ],
    rating: { value: 4.9, count: 168 },
    offer: true
  }
};

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List INSULFILM products",
  description: "List every INSULFILM\u2122 product available on the site (slug, commercial name, page URL, and category).",
  inputSchema: {
    lang: z.enum(["pt", "en", "es"]).default("pt").describe("Language for the returned category label (pt, en, or es).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ lang }) => {
    const items = Object.entries(PDP_PRODUCTS).map(([slug, p]) => ({
      slug,
      name: p.name,
      url: p.url,
      category: p.category?.[lang] ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { products: items }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.23.8";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get INSULFILM product details",
  description: "Return full public details for one INSULFILM\u2122 product: description, technical properties, category, rating, and page URL.",
  inputSchema: {
    slug: z2.string().min(1).describe("Product slug, e.g. 'matrix', 'raystart', 'carbon'."),
    lang: z2.enum(["pt", "en", "es"]).default("pt").describe("Language for text fields.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug, lang }) => {
    const p = PDP_PRODUCTS[slug];
    if (!p) {
      return {
        content: [{ type: "text", text: `No product found for slug '${slug}'.` }],
        isError: true
      };
    }
    const data = {
      slug,
      name: p.name,
      description: p.description[lang],
      url: p.url,
      category: p.category?.[lang] ?? null,
      properties: p.properties.map((prop) => ({
        name: prop.name[lang],
        value: prop.value[lang]
      })),
      rating: p.rating ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/get-faqs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.23.8";

// src/lib/pdpFAQs.ts
var HOME = {
  name: { pt: "In\xEDcio", en: "Home", es: "Inicio" },
  url: "/"
};
var AUTO = {
  name: { pt: "Automotivo", en: "Automotive", es: "Automotriz" },
  url: "/automotivo"
};
var ARQ = {
  name: { pt: "Arquitet\xF4nico", en: "Architectural", es: "Arquitect\xF3nico" },
  url: "/arquitetonico"
};
var SOLAR = { pt: "Solar", en: "Solar", es: "Solar" };
var SECURITY = { pt: "Seguran\xE7a", en: "Security", es: "Seguridad" };
var PPF_LABEL = { pt: "PPF", en: "PPF", es: "PPF" };
var SPF_LABEL = { pt: "SPF", en: "SPF", es: "SPF" };
var product = (name) => ({ pt: name, en: name, es: name });
var autoSolar = (name, url) => [
  HOME,
  AUTO,
  { name: SOLAR, url: "/automotivo/solar" },
  { name: product(name), url }
];
var autoSecurity = (name, url) => [
  HOME,
  AUTO,
  { name: SECURITY, url: "/automotivo/seguranca" },
  { name: product(name), url }
];
var autoPPF = (name, url) => [
  HOME,
  AUTO,
  { name: PPF_LABEL, url: "/automotivo/ppf" },
  { name: product(name), url }
];
var arqSPF = (name, url) => [
  HOME,
  ARQ,
  { name: SPF_LABEL, url: "/arquitetonico/spf" },
  { name: product(name), url }
];
var arqSolarCanonical = (name, slug) => [
  HOME,
  ARQ,
  { name: SOLAR, url: "/pt/arquitetonico/solar" },
  { name: product(name), url: `/pt/arquitetonico/solar/${slug}` }
];
var arqSPFCanonical = (name, slug) => [
  HOME,
  ARQ,
  { name: SPF_LABEL, url: "/pt/arquitetonico/spf" },
  { name: product(name), url: `/pt/arquitetonico/spf/${slug}` }
];
var PDP_META = {
  // ═══ AUTOMOTIVO, SOLAR ═══
  matrix: {
    breadcrumb: autoSolar("INSULFILM\u2122 Matrix", "/matrix"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Matrix?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Matrix film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Matrix?"
        },
        a: {
          pt: "A INSULFILM\u2122 Matrix rejeita at\xE9 75% dos raios infravermelhos.",
          en: "INSULFILM\u2122 Matrix rejects up to 75% of infrared rays.",
          es: "INSULFILM\u2122 Matrix rechaza hasta el 75% de los rayos infrarrojos."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Matrix?",
          en: "How many years of warranty does INSULFILM\u2122 Matrix have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Matrix?"
        },
        a: {
          pt: "A INSULFILM\u2122 Matrix tem 10 anos de garantia contra desbotamento.",
          en: "INSULFILM\u2122 Matrix has a 10-year warranty against fading.",
          es: "INSULFILM\u2122 Matrix tiene 10 a\xF1os de garant\xEDa contra decoloraci\xF3n."
        }
      },
      {
        q: {
          pt: "A pel\xEDcula INSULFILM\u2122 Matrix interfere em GPS, celular ou ped\xE1gio?",
          en: "Does INSULFILM\u2122 Matrix interfere with GPS, cell phone or toll signals?",
          es: "\xBFLa pel\xEDcula INSULFILM\u2122 Matrix interfiere con GPS, m\xF3vil o peaje?"
        },
        a: {
          pt: "N\xE3o. A Matrix \xE9 fabricada com nano cer\xE2mica verdadeira, sem metal, e n\xE3o interfere em sinais de GPS, celular, r\xE1dio ou ped\xE1gios eletr\xF4nicos.",
          en: "No. Matrix is manufactured with true nano-ceramic, metal-free, and does not interfere with GPS, cell phone, radio or electronic toll signals.",
          es: "No. Matrix se fabrica con verdadera nano-cer\xE1mica, sin metal, y no interfiere con se\xF1ales de GPS, m\xF3vil, radio ni peajes electr\xF3nicos."
        }
      },
      {
        q: {
          pt: "Qual a tecnologia da pel\xEDcula INSULFILM\u2122 Matrix?",
          en: "What is the technology of the INSULFILM\u2122 Matrix film?",
          es: "\xBFCu\xE1l es la tecnolog\xEDa de la pel\xEDcula INSULFILM\u2122 Matrix?"
        },
        a: {
          pt: "A Matrix usa Nano Cer\xE2mica da s\xE9rie Ultra Definition.",
          en: "Matrix uses Nano Ceramic technology from the Ultra Definition series.",
          es: "Matrix utiliza Nano Cer\xE1mica de la serie Ultra Definition."
        }
      }
    ]
  },
  "polariz-ultra": {
    breadcrumb: autoSolar("INSULFILM\u2122 Polariz Ultra", "/polariz-ultra"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Polariz Ultra?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Polariz Ultra film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Polariz Ultra?"
        },
        a: {
          pt: "A INSULFILM\u2122 Polariz Ultra rejeita at\xE9 75% dos raios infravermelhos.",
          en: "INSULFILM\u2122 Polariz Ultra rejects up to 75% of infrared rays.",
          es: "INSULFILM\u2122 Polariz Ultra rechaza hasta el 75% de los rayos infrarrojos."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Polariz Ultra?",
          en: "How many years of warranty does INSULFILM\u2122 Polariz Ultra have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Polariz Ultra?"
        },
        a: {
          pt: "A INSULFILM\u2122 Polariz Ultra tem 10 anos de garantia contra desbotamento.",
          en: "INSULFILM\u2122 Polariz Ultra has a 10-year warranty against fading.",
          es: "INSULFILM\u2122 Polariz Ultra tiene 10 a\xF1os de garant\xEDa contra decoloraci\xF3n."
        }
      },
      {
        q: {
          pt: "Qual a tecnologia da pel\xEDcula INSULFILM\u2122 Polariz Ultra?",
          en: "What is the technology of the INSULFILM\u2122 Polariz Ultra film?",
          es: "\xBFCu\xE1l es la tecnolog\xEDa de la pel\xEDcula INSULFILM\u2122 Polariz Ultra?"
        },
        a: {
          pt: "A Polariz Ultra usa tecnologia h\xEDbrida metal-cer\xE2mica de 5\xAA gera\xE7\xE3o, com visual polarizado caracter\xEDstico.",
          en: "Polariz Ultra uses 5th generation hybrid metal-ceramic technology, with a distinctive polarized look.",
          es: "Polariz Ultra utiliza tecnolog\xEDa h\xEDbrida metal-cer\xE1mica de 5.\xAA generaci\xF3n, con un aspecto polarizado caracter\xEDstico."
        }
      }
    ]
  },
  // ═══ AUTOMOTIVO, SEGURANÇA ═══
  antivandalismo13k: {
    breadcrumb: autoSecurity("INSULFILM\u2122 Antivandalismo 13K", "/antivandalismo13k"),
    faqs: [
      {
        q: {
          pt: "Qual a espessura da pel\xEDcula INSULFILM\u2122 Antivandalismo 13K?",
          en: "What is the thickness of the INSULFILM\u2122 Antivandalismo 13K film?",
          es: "\xBFCu\xE1l es el espesor de la pel\xEDcula INSULFILM\u2122 Antivandalismo 13K?"
        },
        a: {
          pt: "A INSULFILM\u2122 Antivandalismo 13K tem 12 mil de espessura, equivalente a 304,8 micras.",
          en: "INSULFILM\u2122 Antivandalismo 13K is 12 mil thick, equivalent to 304.8 microns.",
          es: "INSULFILM\u2122 Antivandalismo 13K tiene 12 mil de espesor, equivalente a 304,8 micras."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Antivandalismo 13K?",
          en: "How many years of warranty does INSULFILM\u2122 Antivandalismo 13K have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Antivandalismo 13K?"
        },
        a: {
          pt: "A INSULFILM\u2122 Antivandalismo 13K tem 5 anos de garantia.",
          en: "INSULFILM\u2122 Antivandalismo 13K has a 5-year warranty.",
          es: "INSULFILM\u2122 Antivandalismo 13K tiene 5 a\xF1os de garant\xEDa."
        }
      },
      {
        q: {
          pt: "A INSULFILM\u2122 Antivandalismo 13K resiste a tentativas de arrombamento?",
          en: "Does INSULFILM\u2122 Antivandalismo 13K resist break-in attempts?",
          es: "\xBFLa INSULFILM\u2122 Antivandalismo 13K resiste intentos de robo?"
        },
        a: {
          pt: "Sim. A constru\xE7\xE3o em dupla lamina\xE7\xE3o retarda arrombamentos, quebras e tentativas de roubo em vidros laterais automotivos.",
          en: "Yes. The double-lamination construction delays break-ins, smash-and-grabs and theft attempts on automotive side windows.",
          es: "S\xED. La construcci\xF3n en doble laminado retarda intentos de robo, roturas y vandalismo en cristales laterales automotrices."
        }
      }
    ]
  },
  skinsafe8k: {
    breadcrumb: autoSecurity("INSULFILM\u2122 SkinSafe 8K", "/skinsafe8k"),
    faqs: [
      {
        q: {
          pt: "Qual a espessura da pel\xEDcula INSULFILM\u2122 SkinSafe 8K?",
          en: "What is the thickness of the INSULFILM\u2122 SkinSafe 8K film?",
          es: "\xBFCu\xE1l es el espesor de la pel\xEDcula INSULFILM\u2122 SkinSafe 8K?"
        },
        a: {
          pt: "A INSULFILM\u2122 SkinSafe 8K tem 7 mil de espessura, equivalente a 177,8 micras.",
          en: "INSULFILM\u2122 SkinSafe 8K is 7 mil thick, equivalent to 177.8 microns.",
          es: "INSULFILM\u2122 SkinSafe 8K tiene 7 mil de espesor, equivalente a 177,8 micras."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 SkinSafe 8K?",
          en: "How many years of warranty does INSULFILM\u2122 SkinSafe 8K have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 SkinSafe 8K?"
        },
        a: {
          pt: "A INSULFILM\u2122 SkinSafe 8K tem 5 anos de garantia.",
          en: "INSULFILM\u2122 SkinSafe 8K has a 5-year warranty.",
          es: "INSULFILM\u2122 SkinSafe 8K tiene 5 a\xF1os de garant\xEDa."
        }
      },
      {
        q: {
          pt: "A INSULFILM\u2122 SkinSafe 8K protege contra estilha\xE7os?",
          en: "Does INSULFILM\u2122 SkinSafe 8K protect against shattered glass?",
          es: "\xBFLa INSULFILM\u2122 SkinSafe 8K protege contra esquirlas?"
        },
        a: {
          pt: "Sim. Ela ret\xE9m os fragmentos do vidro em quebras acidentais, mantendo-os aderidos \xE0 pel\xEDcula e reduzindo o risco de ferimentos nos ocupantes.",
          en: "Yes. It holds glass fragments together in accidental breakage, keeping them adhered to the film and reducing injury risk to occupants.",
          es: "S\xED. Retiene los fragmentos de vidrio en roturas accidentales, manteni\xE9ndolos adheridos a la pel\xEDcula y reduciendo el riesgo de lesiones a los ocupantes."
        }
      }
    ]
  },
  skudoguard: {
    breadcrumb: autoSecurity("INSULFILM\u2122 SkudoGuard", "/skudoguard"),
    faqs: [
      {
        q: {
          pt: "Qual a espessura da pel\xEDcula INSULFILM\u2122 SkudoGuard?",
          en: "What is the thickness of the INSULFILM\u2122 SkudoGuard film?",
          es: "\xBFCu\xE1l es el espesor de la pel\xEDcula INSULFILM\u2122 SkudoGuard?"
        },
        a: {
          pt: "A INSULFILM\u2122 SkudoGuard tem 16 mil de espessura, equivalente a 406,4 micras.",
          en: "INSULFILM\u2122 SkudoGuard is 16 mil thick, equivalent to 406.4 microns.",
          es: "INSULFILM\u2122 SkudoGuard tiene 16 mil de espesor, equivalente a 406,4 micras."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 SkudoGuard?",
          en: "How many years of warranty does INSULFILM\u2122 SkudoGuard have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 SkudoGuard?"
        },
        a: {
          pt: "A INSULFILM\u2122 SkudoGuard tem 10 anos de garantia.",
          en: "INSULFILM\u2122 SkudoGuard has a 10-year warranty.",
          es: "INSULFILM\u2122 SkudoGuard tiene 10 a\xF1os de garant\xEDa."
        }
      },
      {
        q: {
          pt: "A INSULFILM\u2122 SkudoGuard resiste a armas brancas?",
          en: "Does INSULFILM\u2122 SkudoGuard resist bladed weapons?",
          es: "\xBFLa INSULFILM\u2122 SkudoGuard resiste armas blancas?"
        },
        a: {
          pt: "Sim. Com for\xE7a de ruptura de 440 lbs/in, ela atua como escudo contra armas brancas e tentativas de invas\xE3o.",
          en: "Yes. With a break strength of 440 lbs/in, it acts as a shield against bladed weapons and intrusion attempts.",
          es: "S\xED. Con fuerza de ruptura de 440 lbs/in, act\xFAa como escudo contra armas blancas e intentos de intrusi\xF3n."
        }
      }
    ]
  },
  "skudo-ultra": {
    breadcrumb: autoSecurity("INSULFILM\u2122 SkudoUltra", "/skudo-ultra"),
    faqs: [
      {
        q: {
          pt: "Qual a espessura da pel\xEDcula INSULFILM\u2122 SkudoUltra?",
          en: "What is the thickness of the INSULFILM\u2122 SkudoUltra film?",
          es: "\xBFCu\xE1l es el espesor de la pel\xEDcula INSULFILM\u2122 SkudoUltra?"
        },
        a: {
          pt: "A INSULFILM\u2122 SkudoUltra tem 24 mil de espessura, equivalente a 609,6 micras.",
          en: "INSULFILM\u2122 SkudoUltra is 24 mil thick, equivalent to 609.6 microns.",
          es: "INSULFILM\u2122 SkudoUltra tiene 24 mil de espesor, equivalente a 609,6 micras."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 SkudoUltra?",
          en: "How many years of warranty does INSULFILM\u2122 SkudoUltra have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 SkudoUltra?"
        },
        a: {
          pt: "A INSULFILM\u2122 SkudoUltra tem 10 anos de garantia.",
          en: "INSULFILM\u2122 SkudoUltra has a 10-year warranty.",
          es: "INSULFILM\u2122 SkudoUltra tiene 10 a\xF1os de garant\xEDa."
        }
      },
      {
        q: {
          pt: "A INSULFILM\u2122 SkudoUltra \xE9 a pel\xEDcula de seguran\xE7a automotiva mais robusta?",
          en: "Is INSULFILM\u2122 SkudoUltra the most robust automotive security film?",
          es: "\xBFLa INSULFILM\u2122 SkudoUltra es la pel\xEDcula de seguridad automotriz m\xE1s robusta?"
        },
        a: {
          pt: "Sim. Constru\xE7\xE3o tetra laminada com adesivo extremo, \xE9 a pel\xEDcula de seguran\xE7a automotiva mais robusta da marca.",
          en: "Yes. Tetra-laminated construction with extreme adhesive, the most robust automotive security film of the brand.",
          es: "S\xED. Construcci\xF3n tetra laminada con adhesivo extremo, la pel\xEDcula de seguridad automotriz m\xE1s robusta de la marca."
        }
      }
    ]
  },
  // ═══ AUTOMOTIVO, PPF ═══
  "phantom-gloss": {
    breadcrumb: autoPPF("INSULFILM\u2122 Phantom Gloss", "/phantom-gloss"),
    faqs: [
      {
        q: {
          pt: "Qual a espessura do PPF INSULFILM\u2122 Phantom Gloss?",
          en: "What is the thickness of the INSULFILM\u2122 Phantom Gloss PPF?",
          es: "\xBFCu\xE1l es el espesor del PPF INSULFILM\u2122 Phantom Gloss?"
        },
        a: {
          pt: "O INSULFILM\u2122 Phantom Gloss tem 7 mil de espessura, equivalente a aproximadamente 180 microns.",
          en: "INSULFILM\u2122 Phantom Gloss is 7 mil thick, equivalent to approximately 180 microns.",
          es: "INSULFILM\u2122 Phantom Gloss tiene 7 mil de espesor, equivalente a aproximadamente 180 micras."
        }
      },
      {
        q: {
          pt: "Por quantos anos o INSULFILM\u2122 Phantom Gloss \xE9 garantido?",
          en: "For how many years is INSULFILM\u2122 Phantom Gloss warranted?",
          es: "\xBFPor cu\xE1ntos a\xF1os est\xE1 garantizado el INSULFILM\u2122 Phantom Gloss?"
        },
        a: {
          pt: "O INSULFILM\u2122 Phantom Gloss tem 5 anos de garantia contra rachaduras, forma\xE7\xE3o de bolhas e amarelamento causados por defeitos de fabrica\xE7\xE3o.",
          en: "INSULFILM\u2122 Phantom Gloss has a 5-year warranty against cracking, bubbling and yellowing caused by manufacturing defects.",
          es: "INSULFILM\u2122 Phantom Gloss tiene 5 a\xF1os de garant\xEDa contra agrietamiento, formaci\xF3n de burbujas y amarillamiento causados por defectos de fabricaci\xF3n."
        }
      },
      {
        q: {
          pt: "O INSULFILM\u2122 Phantom Gloss tem propriedade auto-regenerativa?",
          en: "Does INSULFILM\u2122 Phantom Gloss have self-healing properties?",
          es: "\xBFEl INSULFILM\u2122 Phantom Gloss tiene propiedades de autorregeneraci\xF3n?"
        },
        a: {
          pt: "Sim. Possui tecnologia auto-regenerativa que recupera microriscos com calor.",
          en: "Yes. It features self-healing technology that recovers micro-scratches with heat.",
          es: "S\xED. Cuenta con tecnolog\xEDa de autorregeneraci\xF3n que recupera microrayones con calor."
        }
      }
    ]
  },
  // ═══ ARQUITETÔNICO, SOLAR ═══
  clear70: {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Clear70", "clear70"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Clear70?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Clear70 film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Clear70?"
        },
        a: {
          pt: "A INSULFILM\u2122 Clear70 rejeita at\xE9 81% dos raios infravermelhos.",
          en: "INSULFILM\u2122 Clear70 rejects up to 81% of infrared rays.",
          es: "INSULFILM\u2122 Clear70 rechaza hasta el 81% de los rayos infrarrojos."
        }
      },
      {
        q: {
          pt: "Qual a transmiss\xE3o de luz vis\xEDvel (VLT) da INSULFILM\u2122 Clear70?",
          en: "What is the visible light transmission (VLT) of INSULFILM\u2122 Clear70?",
          es: "\xBFCu\xE1l es la transmisi\xF3n de luz visible (VLT) de INSULFILM\u2122 Clear70?"
        },
        a: {
          pt: "A INSULFILM\u2122 Clear70 tem 72% de transmiss\xE3o de luz vis\xEDvel (VLT).",
          en: "INSULFILM\u2122 Clear70 has 72% visible light transmission (VLT).",
          es: "INSULFILM\u2122 Clear70 tiene 72% de transmisi\xF3n de luz visible (VLT)."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Clear70?",
          en: "How many years of warranty does INSULFILM\u2122 Clear70 have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Clear70?"
        },
        a: {
          pt: "A INSULFILM\u2122 Clear70 tem garantia de at\xE9 5 anos.",
          en: "INSULFILM\u2122 Clear70 has a warranty of up to 5 years.",
          es: "INSULFILM\u2122 Clear70 tiene garant\xEDa de hasta 5 a\xF1os."
        }
      }
    ]
  },
  naturale: {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Naturale", "naturale"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Naturale?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Naturale film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Naturale?"
        },
        a: {
          pt: "A INSULFILM\u2122 Naturale rejeita at\xE9 81% dos raios infravermelhos nas vers\xF5es mais escuras.",
          en: "INSULFILM\u2122 Naturale rejects up to 81% of infrared rays in the darker versions.",
          es: "INSULFILM\u2122 Naturale rechaza hasta el 81% de los rayos infrarrojos en las versiones m\xE1s oscuras."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Naturale?",
          en: "How many years of warranty does INSULFILM\u2122 Naturale have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Naturale?"
        },
        a: {
          pt: "A INSULFILM\u2122 Naturale tem garantia de at\xE9 10 anos.",
          en: "INSULFILM\u2122 Naturale has a warranty of up to 10 years.",
          es: "INSULFILM\u2122 Naturale tiene garant\xEDa de hasta 10 a\xF1os."
        }
      },
      {
        q: {
          pt: "Qual a tecnologia da pel\xEDcula INSULFILM\u2122 Naturale?",
          en: "What is the technology of the INSULFILM\u2122 Naturale film?",
          es: "\xBFCu\xE1l es la tecnolog\xEDa de la pel\xEDcula INSULFILM\u2122 Naturale?"
        },
        a: {
          pt: "A Naturale usa tecnologia Sputtered Neutra de tonalidade neutra.",
          en: "Naturale uses Sputtered Neutral technology with a neutral tone.",
          es: "Naturale utiliza tecnolog\xEDa Sputtered Neutra de tono neutro."
        }
      }
    ]
  },
  orizzonte70: {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Orizzonte70", "orizzonte70"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Orizzonte70?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Orizzonte70 film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Orizzonte70?"
        },
        a: {
          pt: "A INSULFILM\u2122 Orizzonte70 rejeita at\xE9 93% dos raios infravermelhos.",
          en: "INSULFILM\u2122 Orizzonte70 rejects up to 93% of infrared rays.",
          es: "INSULFILM\u2122 Orizzonte70 rechaza hasta el 93% de los rayos infrarrojos."
        }
      },
      {
        q: {
          pt: "Qual a transmiss\xE3o de luz vis\xEDvel (VLT) da INSULFILM\u2122 Orizzonte70?",
          en: "What is the visible light transmission (VLT) of INSULFILM\u2122 Orizzonte70?",
          es: "\xBFCu\xE1l es la transmisi\xF3n de luz visible (VLT) de INSULFILM\u2122 Orizzonte70?"
        },
        a: {
          pt: "A INSULFILM\u2122 Orizzonte70 tem 68% de transmiss\xE3o de luz vis\xEDvel (VLT).",
          en: "INSULFILM\u2122 Orizzonte70 has 68% visible light transmission (VLT).",
          es: "INSULFILM\u2122 Orizzonte70 tiene 68% de transmisi\xF3n de luz visible (VLT)."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Orizzonte70?",
          en: "How many years of warranty does INSULFILM\u2122 Orizzonte70 have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Orizzonte70?"
        },
        a: {
          pt: "A INSULFILM\u2122 Orizzonte70 tem 10 anos de garantia.",
          en: "INSULFILM\u2122 Orizzonte70 has a 10-year warranty.",
          es: "INSULFILM\u2122 Orizzonte70 tiene 10 a\xF1os de garant\xEDa."
        }
      }
    ]
  },
  "grigio-invertito": {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Grigio Invertito", "grigio-invertito"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Grigio Invertito?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Grigio Invertito film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Grigio Invertito?"
        },
        a: {
          pt: "A INSULFILM\u2122 Grigio Invertito rejeita 75% dos raios infravermelhos.",
          en: "INSULFILM\u2122 Grigio Invertito rejects 75% of infrared rays.",
          es: "INSULFILM\u2122 Grigio Invertito rechaza el 75% de los rayos infrarrojos."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Grigio Invertito?",
          en: "How many years of warranty does INSULFILM\u2122 Grigio Invertito have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Grigio Invertito?"
        },
        a: {
          pt: "A INSULFILM\u2122 Grigio Invertito tem garantia de at\xE9 3 anos.",
          en: "INSULFILM\u2122 Grigio Invertito has a warranty of up to 3 years.",
          es: "INSULFILM\u2122 Grigio Invertito tiene garant\xEDa de hasta 3 a\xF1os."
        }
      },
      {
        q: {
          pt: "Como funciona a privacidade invertida da Grigio Invertito?",
          en: "How does the inverted privacy of Grigio Invertito work?",
          es: "\xBFC\xF3mo funciona la privacidad invertida de Grigio Invertito?"
        },
        a: {
          pt: "A pel\xEDcula \xE9 espelhada na face externa e fum\xEA na face interna, oferecendo privacidade durante o dia e visual fum\xEA de dentro para fora.",
          en: "The film is mirrored on the outer face and smoked on the inner face, offering daytime privacy and a smoked look from inside out.",
          es: "La pel\xEDcula es espejada en la cara exterior y ahumada en la cara interior, ofreciendo privacidad diurna y un aspecto ahumado de dentro hacia fuera."
        }
      }
    ]
  },
  "metallico-argento": {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Metallico Argento", "metallico-argento"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Metallico Argento?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Metallico Argento film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Metallico Argento?"
        },
        a: {
          pt: "A INSULFILM\u2122 Metallico Argento rejeita at\xE9 86% dos raios infravermelhos.",
          en: "INSULFILM\u2122 Metallico Argento rejects up to 86% of infrared rays.",
          es: "INSULFILM\u2122 Metallico Argento rechaza hasta el 86% de los rayos infrarrojos."
        }
      },
      {
        q: {
          pt: "Quanto da energia solar a INSULFILM\u2122 Metallico Argento rejeita?",
          en: "How much solar energy does INSULFILM\u2122 Metallico Argento reject?",
          es: "\xBFCu\xE1nta energ\xEDa solar rechaza INSULFILM\u2122 Metallico Argento?"
        },
        a: {
          pt: "A INSULFILM\u2122 Metallico Argento rejeita at\xE9 80% da energia solar total.",
          en: "INSULFILM\u2122 Metallico Argento rejects up to 80% of total solar energy.",
          es: "INSULFILM\u2122 Metallico Argento rechaza hasta el 80% de la energ\xEDa solar total."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Metallico Argento?",
          en: "How many years of warranty does INSULFILM\u2122 Metallico Argento have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Metallico Argento?"
        },
        a: {
          pt: "A INSULFILM\u2122 Metallico Argento tem 10 anos de garantia.",
          en: "INSULFILM\u2122 Metallico Argento has a 10-year warranty.",
          es: "INSULFILM\u2122 Metallico Argento tiene 10 a\xF1os de garant\xEDa."
        }
      }
    ]
  },
  "reflesso-d-argento": {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Reflesso d'Argento", "reflesso-d-argento"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor da pel\xEDcula INSULFILM\u2122 Reflesso d'Argento?",
          en: "What is the heat rejection of the INSULFILM\u2122 Reflesso d'Argento film?",
          es: "\xBFCu\xE1l es el rechazo de calor de la pel\xEDcula INSULFILM\u2122 Reflesso d'Argento?"
        },
        a: {
          pt: "A INSULFILM\u2122 Reflesso d'Argento rejeita 80% do calor solar.",
          en: "INSULFILM\u2122 Reflesso d'Argento rejects 80% of solar heat.",
          es: "INSULFILM\u2122 Reflesso d'Argento rechaza el 80% del calor solar."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Reflesso d'Argento?",
          en: "How many years of warranty does INSULFILM\u2122 Reflesso d'Argento have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Reflesso d'Argento?"
        },
        a: {
          pt: "A INSULFILM\u2122 Reflesso d'Argento tem garantia de at\xE9 3 anos.",
          en: "INSULFILM\u2122 Reflesso d'Argento has a warranty of up to 3 years.",
          es: "INSULFILM\u2122 Reflesso d'Argento tiene garant\xEDa de hasta 3 a\xF1os."
        }
      },
      {
        q: {
          pt: "Qual a tecnologia da INSULFILM\u2122 Reflesso d'Argento?",
          en: "What is the technology of INSULFILM\u2122 Reflesso d'Argento?",
          es: "\xBFCu\xE1l es la tecnolog\xEDa de INSULFILM\u2122 Reflesso d'Argento?"
        },
        a: {
          pt: "A Reflesso d'Argento usa tecnologia Refletiva Sputtered de excelente custo-benef\xEDcio.",
          en: "Reflesso d'Argento uses Sputtered Reflective technology with excellent cost-benefit.",
          es: "Reflesso d'Argento utiliza tecnolog\xEDa Reflectiva Sputtered con excelente costo-beneficio."
        }
      }
    ]
  },
  petrolio: {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Petrolio", "petrolio"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Petrolio?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Petrolio film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Petrolio?"
        },
        a: {
          pt: "A INSULFILM\u2122 Petrolio rejeita at\xE9 42% dos raios infravermelhos.",
          en: "INSULFILM\u2122 Petrolio rejects up to 42% of infrared rays.",
          es: "INSULFILM\u2122 Petrolio rechaza hasta el 42% de los rayos infrarrojos."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Petrolio?",
          en: "How many years of warranty does INSULFILM\u2122 Petrolio have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Petrolio?"
        },
        a: {
          pt: "A INSULFILM\u2122 Petrolio tem 3 anos de garantia.",
          en: "INSULFILM\u2122 Petrolio has a 3-year warranty.",
          es: "INSULFILM\u2122 Petrolio tiene 3 a\xF1os de garant\xEDa."
        }
      },
      {
        q: {
          pt: "Qual a tonalidade da INSULFILM\u2122 Petrolio?",
          en: "What is the tone of INSULFILM\u2122 Petrolio?",
          es: "\xBFCu\xE1l es la tonalidad de INSULFILM\u2122 Petrolio?"
        },
        a: {
          pt: "A Petrolio \xE9 uma pel\xEDcula h\xEDbrida fum\xEA (charcoal) de alta durabilidade.",
          en: "Petrolio is a hybrid charcoal-tinted film with high durability.",
          es: "Petrolio es una pel\xEDcula h\xEDbrida ahumada (charcoal) de alta durabilidad."
        }
      }
    ]
  },
  "specchiato-bronzo": {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Specchiato Bronzo", "specchiato-bronzo"),
    faqs: [
      {
        q: {
          pt: "Qual a rejei\xE7\xE3o de calor (IR) da pel\xEDcula INSULFILM\u2122 Specchiato Bronzo?",
          en: "What is the heat (IR) rejection of the INSULFILM\u2122 Specchiato Bronzo film?",
          es: "\xBFCu\xE1l es el rechazo de calor (IR) de la pel\xEDcula INSULFILM\u2122 Specchiato Bronzo?"
        },
        a: {
          pt: "A INSULFILM\u2122 Specchiato Bronzo rejeita at\xE9 72% dos raios infravermelhos.",
          en: "INSULFILM\u2122 Specchiato Bronzo rejects up to 72% of infrared rays.",
          es: "INSULFILM\u2122 Specchiato Bronzo rechaza hasta el 72% de los rayos infrarrojos."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Specchiato Bronzo?",
          en: "How many years of warranty does INSULFILM\u2122 Specchiato Bronzo have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Specchiato Bronzo?"
        },
        a: {
          pt: "A INSULFILM\u2122 Specchiato Bronzo tem 10 anos de garantia.",
          en: "INSULFILM\u2122 Specchiato Bronzo has a 10-year warranty.",
          es: "INSULFILM\u2122 Specchiato Bronzo tiene 10 a\xF1os de garant\xEDa."
        }
      },
      {
        q: {
          pt: "Qual a tecnologia da INSULFILM\u2122 Specchiato Bronzo?",
          en: "What is the technology of INSULFILM\u2122 Specchiato Bronzo?",
          es: "\xBFCu\xE1l es la tecnolog\xEDa de INSULFILM\u2122 Specchiato Bronzo?"
        },
        a: {
          pt: "A Specchiato Bronzo usa tecnologia Sputtered Nichrome em tom bronze, com baixo efeito espelho interno.",
          en: "Specchiato Bronzo uses Sputtered Nichrome technology in a bronze tone, with low interior mirror effect.",
          es: "Specchiato Bronzo utiliza tecnolog\xEDa Sputtered Nichrome en tono bronce, con bajo efecto espejo interior."
        }
      }
    ]
  },
  ultravioletti90: {
    breadcrumb: arqSolarCanonical("INSULFILM\u2122 Ultravioletti90", "ultravioletti90"),
    faqs: [
      {
        q: {
          pt: "Quanto a INSULFILM\u2122 Ultravioletti90 bloqueia de raios UV?",
          en: "How much UV does INSULFILM\u2122 Ultravioletti90 block?",
          es: "\xBFCu\xE1nta radiaci\xF3n UV bloquea INSULFILM\u2122 Ultravioletti90?"
        },
        a: {
          pt: "A INSULFILM\u2122 Ultravioletti90 bloqueia mais de 99% dos raios ultravioleta.",
          en: "INSULFILM\u2122 Ultravioletti90 blocks more than 99% of ultraviolet rays.",
          es: "INSULFILM\u2122 Ultravioletti90 bloquea m\xE1s del 99% de los rayos ultravioleta."
        }
      },
      {
        q: {
          pt: "Qual a transmiss\xE3o de luz vis\xEDvel (VLT) da Ultravioletti90?",
          en: "What is the visible light transmission (VLT) of Ultravioletti90?",
          es: "\xBFCu\xE1l es la transmisi\xF3n de luz visible (VLT) de Ultravioletti90?"
        },
        a: {
          pt: "A INSULFILM\u2122 Ultravioletti90 tem 88% de transmiss\xE3o de luz vis\xEDvel, mantendo o vidro praticamente incolor.",
          en: "INSULFILM\u2122 Ultravioletti90 has 88% visible light transmission, keeping the glass virtually colorless.",
          es: "INSULFILM\u2122 Ultravioletti90 tiene 88% de transmisi\xF3n de luz visible, manteniendo el vidrio pr\xE1cticamente incoloro."
        }
      },
      {
        q: {
          pt: "Quantos anos de garantia tem a INSULFILM\u2122 Ultravioletti90?",
          en: "How many years of warranty does INSULFILM\u2122 Ultravioletti90 have?",
          es: "\xBFCu\xE1ntos a\xF1os de garant\xEDa tiene INSULFILM\u2122 Ultravioletti90?"
        },
        a: {
          pt: "A INSULFILM\u2122 Ultravioletti90 tem 5 anos de garantia.",
          en: "INSULFILM\u2122 Ultravioletti90 has a 5-year warranty.",
          es: "INSULFILM\u2122 Ultravioletti90 tiene 5 a\xF1os de garant\xEDa."
        }
      }
    ]
  },
  // ═══ ARQUITETÔNICO, SPF ═══
  "phantom-arquitetonico": {
    breadcrumb: arqSPF("INSULFILM\u2122 Phantom Arquitet\xF4nico", "/phantom-arquitetonico"),
    faqs: [
      {
        q: {
          pt: "Qual a espessura do SPF INSULFILM\u2122 Phantom Arquitet\xF4nico?",
          en: "What is the thickness of the INSULFILM\u2122 Phantom Architectural SPF?",
          es: "\xBFCu\xE1l es el espesor del SPF INSULFILM\u2122 Phantom Arquitect\xF3nico?"
        },
        a: {
          pt: "O INSULFILM\u2122 Phantom Arquitet\xF4nico tem aproximadamente 180 microns de espessura.",
          en: "INSULFILM\u2122 Phantom Architectural is approximately 180 microns thick.",
          es: "INSULFILM\u2122 Phantom Arquitect\xF3nico tiene aproximadamente 180 micras de espesor."
        }
      },
      {
        q: {
          pt: "Por quantos anos o INSULFILM\u2122 Phantom Arquitet\xF4nico \xE9 garantido?",
          en: "For how many years is INSULFILM\u2122 Phantom Architectural warranted?",
          es: "\xBFPor cu\xE1ntos a\xF1os est\xE1 garantizado el INSULFILM\u2122 Phantom Arquitect\xF3nico?"
        },
        a: {
          pt: "O INSULFILM\u2122 Phantom Arquitet\xF4nico tem 5 anos de garantia.",
          en: "INSULFILM\u2122 Phantom Architectural has a 5-year warranty.",
          es: "INSULFILM\u2122 Phantom Arquitect\xF3nico tiene 5 a\xF1os de garant\xEDa."
        }
      },
      {
        q: {
          pt: "O que \xE9 um SPF (Surface Protection Film)?",
          en: "What is an SPF (Surface Protection Film)?",
          es: "\xBFQu\xE9 es un SPF (Surface Protection Film)?"
        },
        a: {
          pt: "SPF \xE9 uma pel\xEDcula de prote\xE7\xE3o de superf\xEDcie que preserva o brilho original contra micro-riscos, manchas \xE1cidas e desgaste em superf\xEDcies brilhosas arquitet\xF4nicas.",
          en: "SPF is a surface protection film that preserves the original gloss against micro-scratches, acid stains and wear on architectural high-gloss surfaces.",
          es: "SPF es una pel\xEDcula de protecci\xF3n de superficies que preserva el brillo original contra microrayones, manchas \xE1cidas y desgaste en superficies brillantes arquitect\xF3nicas."
        }
      }
    ]
  },
  // ═══ ARQUITETÔNICO, SPF (entradas dedicadas, separadas da auto) ═══
  "phantom-gloss-spf": {
    breadcrumb: arqSPFCanonical("INSULFILM\u2122 Phantom Gloss", "phantom-gloss"),
    faqs: [
      {
        q: {
          pt: "A Phantom Gloss arquitet\xF4nica \xE9 a mesma que a automotiva?",
          en: "Is architectural Phantom Gloss the same as automotive?",
          es: "\xBFLa Phantom Gloss arquitect\xF3nica es la misma que la automotriz?"
        },
        a: {
          pt: "N\xE3o. S\xE3o da mesma fam\xEDlia Phantom, mas produtos distintos: a vers\xE3o arquitet\xF4nica \xE9 SPF (Surface Protection Film) para m\xE1rmore, lacado e madeira; a automotiva \xE9 PPF (Paint Protection Film) para pintura de ve\xEDculos.",
          en: "No. They belong to the same Phantom family but are distinct products: the architectural version is SPF (Surface Protection Film) for marble, lacquer and wood; the automotive is PPF (Paint Protection Film) for vehicle paint.",
          es: "No. Pertenecen a la misma familia Phantom pero son productos distintos: la versi\xF3n arquitect\xF3nica es SPF (Surface Protection Film) para m\xE1rmol, lacado y madera; la automotriz es PPF (Paint Protection Film) para pintura de veh\xEDculos."
        }
      },
      {
        q: {
          pt: "Em que superf\xEDcies a Phantom Gloss arquitet\xF4nica \xE9 aplicada?",
          en: "On which surfaces is architectural Phantom Gloss applied?",
          es: "\xBFEn qu\xE9 superficies se aplica la Phantom Gloss arquitect\xF3nica?"
        },
        a: {
          pt: "Superf\xEDcies de acabamento brilhoso: m\xE1rmore polido, granito polido, lacado, madeira envernizada e vidro de alto padr\xE3o.",
          en: "High-gloss surfaces: polished marble, polished granite, lacquered surfaces, varnished wood and premium glass.",
          es: "Superficies de acabado brillante: m\xE1rmol pulido, granito pulido, lacado, madera barnizada y vidrio de alto est\xE1ndar."
        }
      },
      {
        q: {
          pt: "Qual a espessura e garantia da Phantom Gloss arquitet\xF4nica?",
          en: "What is the thickness and warranty of architectural Phantom Gloss?",
          es: "\xBFCu\xE1l es el espesor y garant\xEDa de la Phantom Gloss arquitect\xF3nica?"
        },
        a: {
          pt: "180 microns de espessura, com garantia de at\xE9 5 anos contra falhas da pel\xEDcula.",
          en: "180 microns thick, with up to 5 years warranty against film failure.",
          es: "180 micras de espesor, con garant\xEDa de hasta 5 a\xF1os contra fallas de la pel\xEDcula."
        }
      }
    ]
  },
  "phantom-matte": {
    breadcrumb: arqSPFCanonical("INSULFILM\u2122 Phantom Matte", "phantom-matte"),
    faqs: [
      {
        q: {
          pt: "A Phantom Matte preserva o acabamento fosco original?",
          en: "Does Phantom Matte preserve the original matte finish?",
          es: "\xBFLa Phantom Matte preserva el acabado mate original?"
        },
        a: {
          pt: "Sim. A formula\xE7\xE3o \xE9 espec\xEDfica para acabamentos foscos, n\xE3o adiciona brilho nem altera a textura visual do material original.",
          en: "Yes. The formulation is specific to matte finishes, it does not add gloss nor alter the visual texture of the original material.",
          es: "S\xED. La formulaci\xF3n es espec\xEDfica para acabados mate, no a\xF1ade brillo ni altera la textura visual del material original."
        }
      },
      {
        q: {
          pt: "Qual a diferen\xE7a entre Phantom Matte e Phantom Gloss arquitet\xF4nicas?",
          en: "What is the difference between architectural Phantom Matte and Phantom Gloss?",
          es: "\xBFCu\xE1l es la diferencia entre Phantom Matte y Phantom Gloss arquitect\xF3nicas?"
        },
        a: {
          pt: "Mesma fam\xEDlia, mesma tecnologia base (180 microns SPF). A Gloss preserva acabamento brilhoso (m\xE1rmore polido, lacado); a Matte preserva acabamento fosco (m\xE1rmore matte, lacado fosco, madeira natural).",
          en: "Same family, same base technology (180 microns SPF). Gloss preserves high-gloss finish (polished marble, lacquered); Matte preserves matte finish (matte marble, matte lacquered, natural wood).",
          es: "Misma familia, misma tecnolog\xEDa base (180 micras SPF). Gloss preserva acabado brillante (m\xE1rmol pulido, lacado); Matte preserva acabado mate (m\xE1rmol mate, lacado mate, madera natural)."
        }
      },
      {
        q: {
          pt: "Quais s\xE3o as aplica\xE7\xF5es t\xEDpicas da Phantom Matte?",
          en: "What are typical Phantom Matte applications?",
          es: "\xBFCu\xE1les son las aplicaciones t\xEDpicas de Phantom Matte?"
        },
        a: {
          pt: "M\xE1rmore preto matte, lacado fosco, madeira em acabamento natural ou velado, projetos de design contempor\xE2neo onde paleta matte \xE9 parte da identidade visual.",
          en: "Matte black marble, matte lacquered surfaces, wood in natural or veiled finish, contemporary design projects where the matte palette is part of the visual identity.",
          es: "M\xE1rmol negro mate, lacado mate, madera en acabado natural o velado, proyectos de dise\xF1o contempor\xE1neo donde la paleta mate es parte de la identidad visual."
        }
      }
    ]
  }
};
var pickFAQs = (faqs, lang) => faqs.map((f) => ({ q: f.q[lang], a: f.a[lang] }));
var getPDPFaqs = (slug, lang) => {
  const meta = PDP_META[slug];
  if (!meta) return null;
  return pickFAQs(meta.faqs, lang);
};

// src/lib/mcp/tools/get-faqs.ts
var get_faqs_default = defineTool3({
  name: "get_faqs",
  title: "Get product FAQs",
  description: "Return the public FAQ list (question/answer pairs) for one INSULFILM\u2122 product page.",
  inputSchema: {
    slug: z3.string().min(1).describe("Product slug, e.g. 'matrix', 'raystart', 'carbon'."),
    lang: z3.enum(["pt", "en", "es"]).default("pt").describe("Language for the FAQs.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug, lang }) => {
    const faqs = getPDPFaqs(slug, lang);
    if (!faqs) {
      return {
        content: [{ type: "text", text: `No FAQs found for slug '${slug}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(faqs, null, 2) }],
      structuredContent: { faqs }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "insulfilm-mcp",
  title: "INSULFILM\u2122 Site MCP",
  version: "0.1.0",
  instructions: "Public tools for the INSULFILM\u2122 site. Use `list_products` to discover products, `get_product` for full specs of a product by slug, and `get_faqs` to fetch the public FAQ for a product. All content is public and available in Portuguese (pt), English (en), and Spanish (es).",
  tools: [list_products_default, get_product_default, get_faqs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
